// Package config persists user preferences (currently: chosen backend) to
// ~/.config/llmterm/config.toml. Format is intentionally trivial — one
// key=value line per setting — so we don't pull in a TOML dependency.
package config

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const DefaultBackend = "claude"

type Config struct {
	Backend string
}

func Path() string {
	if x := os.Getenv("XDG_CONFIG_HOME"); x != "" {
		return filepath.Join(x, "llmterm", "config.toml")
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "llmterm", "config.toml")
}

func Load() Config {
	c := Config{Backend: DefaultBackend}
	f, err := os.Open(Path())
	if err != nil {
		return c
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		k = strings.TrimSpace(k)
		v = strings.TrimSpace(strings.Trim(strings.TrimSpace(v), `"`))
		switch k {
		case "backend":
			c.Backend = v
		}
	}
	return c
}

func Save(c Config) error {
	p := Path()
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	body := fmt.Sprintf("# llmterm config — generated by `llmterm use`\nbackend = %q\n", c.Backend)
	return os.WriteFile(p, []byte(body), 0o600)
}
